manifest_version = 2
name = "On Demand Migration with Backblaze B2 and Fastly"
description = "Fastly Compute@Edge app demo for Tech Day 2022"
authors = ["evangelism@backblaze.com"]
language = "javascript"
